/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bdd.guiswingorderwinbdd;

/**
 *
 * @author shiny
 *
 * @version 1.0
 *
 */
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import java.util.regex.Pattern; // para las validaciones

public class GuiSwingOrderWinBDD extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiSwingOrderWinBDD.class.getName());

    /**
     * Creates new form GuiSwingOrderWinBDD
     */
    public GuiSwingOrderWinBDD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        btnActualizarFecha = new javax.swing.JButton();
        radioRestaurante = new javax.swing.JRadioButton();
        radioParaLlevar = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnComprobarEmail = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        radioTarjeta = new javax.swing.JRadioButton();
        radioEfectivo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        comboPropina = new javax.swing.JComboBox<>();
        checkFactura = new javax.swing.JCheckBox();
        btnInfo = new javax.swing.JButton();
        btnVerPedido = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        btnCalculadora = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TakeOrderAp v.1 por Blagovest Doukov Dimitrova");
        setPreferredSize(new java.awt.Dimension(563, 663));
        setResizable(false);

        jLabel1.setText("Fecha y Hora:");

        lblFechaHora.setText("\" \"");

        btnActualizarFecha.setText("Actualizar");
        btnActualizarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioRestaurante);
        radioRestaurante.setText("Para comer aqui");
        radioRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRestauranteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioParaLlevar);
        radioParaLlevar.setText("Para llevar");
        radioParaLlevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioParaLlevarActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de mesa:");

        txtNumeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroMesaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Cliente: ");

        jLabel4.setText("Email:");

        btnComprobarEmail.setText("Comprobar Email");
        btnComprobarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarEmailActionPerformed(evt);
            }
        });

        jLabel5.setText("Comentarios:");

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        jScrollPane2.setViewportView(txtComentarios);

        jLabel6.setText("Total: ");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioTarjeta);
        radioTarjeta.setText("Tarjeta");

        buttonGroup2.add(radioEfectivo);
        radioEfectivo.setText("Efectivo");

        jLabel7.setText("Propina:");

        comboPropina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Propina :(", "5%", "10%", "15%", "20%" }));
        comboPropina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPropinaActionPerformed(evt);
            }
        });

        checkFactura.setText("Solicitar Factura");
        checkFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFacturaActionPerformed(evt);
            }
        });

        btnInfo.setText("Informacion");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnVerPedido.setText("Ver Pedido");
        btnVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidoActionPerformed(evt);
            }
        });

        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        btnCalculadora.setText("Calculadora");
        btnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Savate", 1, 16)); // NOI18N
        jLabel8.setText("GUI SWING ORDER WIN BY BLAGO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcercaDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFechaHora))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnActualizarFecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnComprobarEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreCliente)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioRestaurante)
                                    .addComponent(radioParaLlevar)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioEfectivo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioTarjeta)
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkFactura)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFechaHora))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarFecha)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprobarEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioParaLlevar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioEfectivo)
                            .addComponent(jLabel7)
                            .addComponent(comboPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioTarjeta)
                            .addComponent(checkFactura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInfo)
                            .addComponent(btnVerPedido)
                            .addComponent(btnAcercaDe)
                            .addComponent(btnCalculadora)
                            .addComponent(btnSalir))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarFechaActionPerformed
        // 1. Obtenemos la fecha y hora actuales del sistema
        LocalDateTime ahora = LocalDateTime.now();

        // 2. Le damos formato que se pueda leer
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String fechaHoraFormateada = ahora.format(formato);

        // 3. Ponemos el texto en el label
        lblFechaHora.setText(fechaHoraFormateada);
    }//GEN-LAST:event_btnActualizarFechaActionPerformed

    private void radioRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRestauranteActionPerformed
        // Se ejecuta esto cuando marcan la casilla de tomar en el restaurante
        txtNumeroMesa.setEnabled(true); // Habilitamos el campo de texto para que el cliente escriba el numero de mesa
        txtNumeroMesa.setText(""); // Vaciamos el textlabel para que el cliente pueda escribir
    }//GEN-LAST:event_radioRestauranteActionPerformed

    private void radioParaLlevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioParaLlevarActionPerformed
        txtNumeroMesa.setEnabled(false); // Deshabilitamos el campo de texto si el pedido es para llevar
        txtNumeroMesa.setText("0"); // Ponemos el valor a 0
    }//GEN-LAST:event_radioParaLlevarActionPerformed

    private void txtNumeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMesaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void comboPropinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPropinaActionPerformed

    private void checkFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFacturaActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // 1. Pillamos la informacion
        String so = System.getProperty("os.name");
        String usuario = System.getProperty("user.name");
        String fecha = java.time.LocalDateTime.now().format(
                java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")
        );

        // 2. Hacemos el mensaje con html para que se ponga con b en negrita, era la opcion mas facil y la unica que me se hasta el momento
        String mensaje = "<html><b>Bienvenido a mi app</b><br><br>"
                + "<b>Sistema Operativo:</b> " + so + "<br>"
                + "<b>Usuario:</b> " + usuario + "<br>"
                + "<b>Hora y Fecha actual:</b> " + fecha
                + "</html>";

        // 3. Mostramos el mensaje en un JOptionPane
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Información del Sistema",
                JOptionPane.INFORMATION_MESSAGE // icono de información
        );
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // 1. Enseñamos al cliente un dialogo de confirmacion
        String mensajePregunta = "<html>¿Estas seguro de que quieres <b>SALIR</b>?</html>";
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                mensajePregunta,
                "Confirma que quieres salir",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        // 2. Ahora comprobamos que ha pulsado el cliente
        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el cliente pusla que quiere salir mostraremos un mensaje de despedida
            String mensajeDespedida = "<html><b>Ya nos las veremos, gracias por usar nuestra aplicacion...</b></html>";
            JOptionPane.showMessageDialog(
                    this,
                    mensajeDespedida,
                    "Hasta pronto :)",
                    JOptionPane.INFORMATION_MESSAGE
            );
            // 3. Cerramos la aplicacion
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidoActionPerformed

        // Antes de nada ponemos la validacion para que pare si algo no esta validado correctamente
        if (validarFormulario() == false) {
            return; // Si la validacion falla, no sigue
        }

        // 1. Ponemos  textos de ventana
        StringBuilder resumen = new StringBuilder();
        resumen.append("<html><b>RESUMEN DEL PEDIDO</b><br><br>");

        // 2. Recogemos los datos de los textfield
        resumen.append("<b>Cliente: </b>").append(txtNombreCliente.getText().trim()).append("<br>"); // utilizo trim para eliminar espacios en blanco al inicio y al final
        resumen.append("<b>Email: </b>").append(txtEmail.getText().trim()).append("<br>");
        resumen.append("<b>Total: </b>").append(txtTotal.getText().trim()).append("<br>");

        // 3. Ahora recogemos los datos de los radiobuttons de para llevar o en restaurante
        if (radioRestaurante.isSelected()) {
            resumen.append("<b>Tipo: </b> En restaurante<br>");
            resumen.append("<b>Mesa: </b> ").append(txtNumeroMesa.getText().trim()).append("<br>");
        } else if (radioParaLlevar.isSelected()) {
            resumen.append("<b>Tipo: </b> Para llevar<br>");
            // Como he hecho la validacion abajo quito esto
            //} else {
            //    resumen.append("Tipo: No has seleccionado donde quieres comer\n");
        }

        // 4. Recogemos datos de los radiobutton de pago
        if (radioEfectivo.isSelected()) {
            resumen.append("<b>Pago: </b> Efectivo<br>");
        } else if (radioTarjeta.isSelected()) {
            resumen.append("<b>Pago: </b> Tarjeta<br>");
            // Como he hecho la validacion abajo quito esto
            //} else {
            //    resumen.append("Pago: No has seleccionado con que quieres pagar, no querrás hacer un sinpa??");
        }

        // 5. Recogemos los datos de la propina
        resumen.append("<b>Propina: </b>").append(comboPropina.getSelectedItem().toString()).append("<br>");

        // 6. Recogemos los datos de la factura
        if (checkFactura.isSelected()) {
            resumen.append("<b>Factura: </b> Si<br>");
        } else {
            resumen.append("<b>Factura: </b> No<br>");
        }

        // 7. Recogemos los datos de los comentarios
        resumen.append("<br><b>Comentarios: </b><br>");
        String comentarios = txtComentarios.getText().replace("\n", "<br>");
        resumen.append(comentarios);

        resumen.append("</html>");

        // 8. Por ultimo mostramos todo
        JOptionPane.showMessageDialog(
                this,
                resumen.toString(), // convertimos el stringbuilder en un string
                "Resumen del pedido",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnVerPedidoActionPerformed

    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadoraActionPerformed
        // 1. Obtenemos el sistema operativo 
        String OS = System.getProperty("os.name").toLowerCase(); // lo obtenemos en minusculas
        String comando = "";

        // 2. Decimos que comando queremos que ejecute
        if (OS.contains("win")) {
            comando = "calc"; // calculadora de windows
        } else if (OS.contains("nix") || OS.contains("nux") || OS.contains("linux")) {
            comando = "mate-calculator";
        } else {
            // si no hay linux o windows no se hace nada
        }

        // 3. Intentamos ejecutar el comando
        if (!comando.isEmpty()) {
            try {
                // ejecutamos el comando del sistema
                Runtime.getRuntime().exec(comando);

            } catch (java.io.IOException e) {
                // si hay errores
                JOptionPane.showMessageDialog(
                        this,
                        "No se ha podido abrir la calculadora. Error: " + e.getMessage(),
                        "Error al ejecutar",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } else {
            // 4. Si el sistema operativo no es compatible
            JOptionPane.showMessageDialog(
                    this,
                    "La calculadora no es compatible con tu Sistema Operativo (" + OS + ").",
                    "Sistema Operativo no compatible",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCalculadoraActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        // Construimos el mensaje
        String msg
                = "<html><b>Desarrollador: </b> Blagovest Doukov Dimitrova<br>"
                + "<b>Aplicacion: </b> TakeOrderApp<br>"
                + "<b>Version: </b> 1.0</html>";

        // Mostramos el mensaje
        JOptionPane.showMessageDialog(
                this,
                msg,
                "Acerca de",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private boolean esEmailValido(String email) {
    // Esta es la expresión regular correcta
    String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
    Pattern pat = Pattern.compile(emailRegex);
    
    if (email == null) {
        return false;
    }
    // Comprueba si el email coincide con el patrón
    return pat.matcher(email).matches();
}
    
    private void btnComprobarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarEmailActionPerformed
        String email = txtEmail.getText().trim();

        // 1. Comprobamos si el campo esta vacio
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "El campo de email está vacío, tranquilidad se puede...",
                    "Email Vacío",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        // 2. Llamamos a la funcion 
        if (esEmailValido(email)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ta bien escrito tranqui",
                    "Email Válido",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No lo has escrito bien maquina, ahora te lo borro y vuelve a escribir venga",
                    "Email Inválido",
                    JOptionPane.ERROR_MESSAGE
            );
            txtEmail.setText("");
        }

    }//GEN-LAST:event_btnComprobarEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiSwingOrderWinBDD().setVisible(true));
    }

    // Vamos a poner aqui un metodo para que revise todas las validaciones de los datos y no se guarden cuando no esten correctos
    private boolean validarFormulario() {
        // 1. Validacion del nombre
        if (txtNombreCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Es obligatorio que pongas un nombre",
                    "Error de verificacion",
                    JOptionPane.ERROR_MESSAGE
            );
            txtNombreCliente.requestFocus(); // Ponemos el cursor en el campo
            return false; // paramos la validacion
        }

        // 2. Validamos el tipo de pedido
        if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes seleccionar si vas a comer aqui o va a ser para llevar",
                    "Error de validacion",
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        // 3. Validamos el numero de mesa
        if (radioRestaurante.isSelected()) {
            String mesa = txtNumeroMesa.getText().trim();
            if (mesa.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Para pedidos en restaurante el numero de mesa es obligatorio",
                        "Error de validacion",
                        JOptionPane.ERROR_MESSAGE
                );
                return false;
            }

            try {
                int numMesa = Integer.parseInt(mesa);
                if (numMesa <= 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "El numero de mesa tiene que ser mayor a 0",
                            "Error de validacion",
                            JOptionPane.ERROR_MESSAGE
                    );
                    txtNumeroMesa.requestFocus();
                    return false;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "El numero de mesa deber un numero valido",
                        "Error de validacion",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNumeroMesa.requestFocus();
                return false;
            }
        }

        // 4. Validamos email si no esta vacio
        String email = txtEmail.getText().trim();
        if (!email.isEmpty()) {
            String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
            Pattern pat = Pattern.compile(emailRegex);
            if (!pat.matcher(email).matches()) {
                JOptionPane.showMessageDialog(
                        this,
                        "El formato de email no es valido",
                        "Error de validacion",
                        JOptionPane.ERROR_MESSAGE
                );
                txtEmail.requestFocus();
                return false;
            }
        }

        // 5. Validar el total, obligatoriamente
        if (txtTotal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "El total es obligatorio",
                    "Error de validacion",
                    JOptionPane.ERROR_MESSAGE
            );
            txtTotal.requestFocus();
            return false;
        }

        // 6. Validar metodo de pago
        if (buttonGroup2.getSelection() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No has seleccionado con que quieres pagar, no querrás hacer un sinpa??",
                    "Error de validacion",
                    JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        // Si ha pasado todas las validaciones
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnActualizarFecha;
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton btnComprobarEmail;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkFactura;
    private javax.swing.JComboBox<String> comboPropina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JRadioButton radioEfectivo;
    private javax.swing.JRadioButton radioParaLlevar;
    private javax.swing.JRadioButton radioRestaurante;
    private javax.swing.JRadioButton radioTarjeta;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
